// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.39.0-15-geec8928
#include <stan/model/model_header.hpp>
namespace model_weight_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 77> locations_array__ =
  {" (found before start of program)",
  " (in 'weight', line 37, column 2 to column 17)",
  " (in 'weight', line 38, column 2 to column 17)",
  " (in 'weight', line 39, column 2 to column 18)",
  " (in 'weight', line 40, column 2 to column 22)",
  " (in 'weight', line 41, column 2 to column 30)",
  " (in 'weight', line 42, column 2 to column 26)",
  " (in 'weight', line 43, column 2 to column 24)",
  " (in 'weight', line 44, column 2 to column 24)",
  " (in 'weight', line 45, column 2 to column 32)",
  " (in 'weight', line 46, column 2 to column 35)",
  " (in 'weight', line 49, column 2 to column 40)",
  " (in 'weight', line 50, column 2 to column 64)",
  " (in 'weight', line 51, column 2 to column 59)",
  " (in 'weight', line 52, column 2 to column 27)",
  " (in 'weight', line 80, column 2 to column 23)",
  " (in 'weight', line 81, column 2 to column 24)",
  " (in 'weight', line 54, column 4 to line 57, column 36)",
  " (in 'weight', line 53, column 20 to line 58, column 3)",
  " (in 'weight', line 53, column 2 to line 58, column 3)",
  " (in 'weight', line 83, column 4 to line 84, column 39)",
  " (in 'weight', line 85, column 4 to column 33)",
  " (in 'weight', line 86, column 4 to line 89, column 34)",
  " (in 'weight', line 82, column 20 to line 90, column 3)",
  " (in 'weight', line 82, column 2 to line 90, column 3)",
  " (in 'weight', line 61, column 2 to column 61)",
  " (in 'weight', line 62, column 2 to column 59)",
  " (in 'weight', line 63, column 2 to column 62)",
  " (in 'weight', line 64, column 2 to column 42)",
  " (in 'weight', line 65, column 2 to column 59)",
  " (in 'weight', line 66, column 2 to column 51)",
  " (in 'weight', line 67, column 2 to column 48)",
  " (in 'weight', line 68, column 2 to column 25)",
  " (in 'weight', line 69, column 2 to column 33)",
  " (in 'weight', line 70, column 2 to column 40)",
  " (in 'weight', line 72, column 4 to column 53)",
  " (in 'weight', line 71, column 23 to line 73, column 3)",
  " (in 'weight', line 71, column 2 to line 73, column 3)",
  " (in 'weight', line 10, column 2 to column 20)",
  " (in 'weight', line 11, column 2 to column 21)",
  " (in 'weight', line 12, column 2 to column 21)",
  " (in 'weight', line 13, column 8 to column 12)",
  " (in 'weight', line 13, column 2 to column 45)",
  " (in 'weight', line 14, column 8 to column 12)",
  " (in 'weight', line 14, column 2 to column 45)",
  " (in 'weight', line 15, column 18 to column 22)",
  " (in 'weight', line 15, column 2 to column 33)",
  " (in 'weight', line 16, column 18 to column 22)",
  " (in 'weight', line 16, column 2 to column 31)",
  " (in 'weight', line 18, column 2 to column 26)",
  " (in 'weight', line 19, column 2 to column 35)",
  " (in 'weight', line 20, column 2 to column 25)",
  " (in 'weight', line 21, column 2 to column 34)",
  " (in 'weight', line 22, column 2 to column 26)",
  " (in 'weight', line 23, column 2 to column 35)",
  " (in 'weight', line 24, column 2 to column 35)",
  " (in 'weight', line 25, column 2 to column 44)",
  " (in 'weight', line 26, column 2 to column 40)",
  " (in 'weight', line 27, column 2 to column 39)",
  " (in 'weight', line 28, column 2 to column 35)",
  " (in 'weight', line 31, column 2 to column 16)",
  " (in 'weight', line 32, column 2 to column 34)",
  " (in 'weight', line 33, column 9 to column 13)",
  " (in 'weight', line 33, column 2 to column 63)",
  " (in 'weight', line 34, column 9 to column 13)",
  " (in 'weight', line 34, column 2 to column 40)",
  " (in 'weight', line 44, column 9 to column 14)",
  " (in 'weight', line 45, column 9 to column 14)",
  " (in 'weight', line 46, column 9 to column 14)",
  " (in 'weight', line 46, column 16 to column 21)",
  " (in 'weight', line 49, column 9 to column 14)",
  " (in 'weight', line 50, column 9 to column 14)",
  " (in 'weight', line 51, column 9 to column 14)",
  " (in 'weight', line 51, column 16 to column 21)",
  " (in 'weight', line 52, column 9 to column 13)",
  " (in 'weight', line 80, column 9 to column 13)",
  " (in 'weight', line 81, column 9 to column 13)"};
#include <stan_meta_header.hpp>
class model_weight final : public model_base_crtp<model_weight> {
private:
  int nObs;
  int nSite;
  int nYear;
  std::vector<int> site;
  std::vector<int> year;
  Eigen::Matrix<double,-1,1> diameter_data__;
  Eigen::Matrix<double,-1,1> weight_data__;
  double prior_intercept_mu;
  double prior_intercept_sd;
  double prior_diameter_mu;
  double prior_diameter_sd;
  double prior_diameter2_mu;
  double prior_diameter2_sd;
  double prior_sd_site_rate;
  double prior_sd_site_diameter_rate;
  double prior_sd_site_year_rate;
  double prior_sd_residual_rate;
  int prior_only;
  double nu;
  double log_diameter_ref;
  Eigen::Matrix<double,-1,1> log_diameter_data__;
  Eigen::Matrix<double,-1,1> log_weight_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> diameter{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> weight{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> log_diameter{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> log_weight{nullptr, 0};
public:
  ~model_weight() {}
  model_weight(stan::io::var_context& context__, unsigned int
               random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_weight_namespace::model_weight";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 38;
      context__.validate_dims("data initialization", "nObs", "int",
        std::vector<size_t>{});
      nObs = std::numeric_limits<int>::min();
      current_statement__ = 38;
      nObs = context__.vals_i("nObs")[(1 - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "nObs", nObs, 0);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "nSite", "int",
        std::vector<size_t>{});
      nSite = std::numeric_limits<int>::min();
      current_statement__ = 39;
      nSite = context__.vals_i("nSite")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "nSite", nSite, 1);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "nYear", "int",
        std::vector<size_t>{});
      nYear = std::numeric_limits<int>::min();
      current_statement__ = 40;
      nYear = context__.vals_i("nYear")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "nYear", nYear, 1);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("site", "nObs", nObs);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "site", "int",
        std::vector<size_t>{static_cast<size_t>(nObs)});
      site = std::vector<int>(nObs, std::numeric_limits<int>::min());
      current_statement__ = 42;
      site = context__.vals_i("site");
      current_statement__ = 42;
      stan::math::check_greater_or_equal(function__, "site", site, 1);
      current_statement__ = 42;
      stan::math::check_less_or_equal(function__, "site", site, nSite);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("year", "nObs", nObs);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "year", "int",
        std::vector<size_t>{static_cast<size_t>(nObs)});
      year = std::vector<int>(nObs, std::numeric_limits<int>::min());
      current_statement__ = 44;
      year = context__.vals_i("year");
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "year", year, 1);
      current_statement__ = 44;
      stan::math::check_less_or_equal(function__, "year", year, nYear);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("diameter", "nObs", nObs);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "diameter", "double",
        std::vector<size_t>{static_cast<size_t>(nObs)});
      diameter_data__ = Eigen::Matrix<double,-1,1>::Constant(nObs,
                          std::numeric_limits<double>::quiet_NaN());
      new (&diameter)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(diameter_data__.data(), nObs);
      {
        std::vector<local_scalar_t__> diameter_flat__;
        current_statement__ = 46;
        diameter_flat__ = context__.vals_r("diameter");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
          stan::model::assign(diameter, diameter_flat__[(pos__ - 1)],
            "assigning variable diameter", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "diameter", diameter, 0);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("weight", "nObs", nObs);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "weight", "double",
        std::vector<size_t>{static_cast<size_t>(nObs)});
      weight_data__ = Eigen::Matrix<double,-1,1>::Constant(nObs,
                        std::numeric_limits<double>::quiet_NaN());
      new (&weight)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(weight_data__.data(), nObs);
      {
        std::vector<local_scalar_t__> weight_flat__;
        current_statement__ = 48;
        weight_flat__ = context__.vals_r("weight");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
          stan::model::assign(weight, weight_flat__[(pos__ - 1)],
            "assigning variable weight", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "weight", weight, 0);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "prior_intercept_mu",
        "double", std::vector<size_t>{});
      prior_intercept_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      prior_intercept_mu = context__.vals_r("prior_intercept_mu")[(1 - 1)];
      current_statement__ = 50;
      context__.validate_dims("data initialization", "prior_intercept_sd",
        "double", std::vector<size_t>{});
      prior_intercept_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 50;
      prior_intercept_sd = context__.vals_r("prior_intercept_sd")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "prior_intercept_sd",
        prior_intercept_sd, 0);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "prior_diameter_mu",
        "double", std::vector<size_t>{});
      prior_diameter_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 51;
      prior_diameter_mu = context__.vals_r("prior_diameter_mu")[(1 - 1)];
      current_statement__ = 52;
      context__.validate_dims("data initialization", "prior_diameter_sd",
        "double", std::vector<size_t>{});
      prior_diameter_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 52;
      prior_diameter_sd = context__.vals_r("prior_diameter_sd")[(1 - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "prior_diameter_sd",
        prior_diameter_sd, 0);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "prior_diameter2_mu",
        "double", std::vector<size_t>{});
      prior_diameter2_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 53;
      prior_diameter2_mu = context__.vals_r("prior_diameter2_mu")[(1 - 1)];
      current_statement__ = 54;
      context__.validate_dims("data initialization", "prior_diameter2_sd",
        "double", std::vector<size_t>{});
      prior_diameter2_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 54;
      prior_diameter2_sd = context__.vals_r("prior_diameter2_sd")[(1 - 1)];
      current_statement__ = 54;
      stan::math::check_greater_or_equal(function__, "prior_diameter2_sd",
        prior_diameter2_sd, 0);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "prior_sd_site_rate",
        "double", std::vector<size_t>{});
      prior_sd_site_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 55;
      prior_sd_site_rate = context__.vals_r("prior_sd_site_rate")[(1 - 1)];
      current_statement__ = 55;
      stan::math::check_greater_or_equal(function__, "prior_sd_site_rate",
        prior_sd_site_rate, 0);
      current_statement__ = 56;
      context__.validate_dims("data initialization",
        "prior_sd_site_diameter_rate", "double", std::vector<size_t>{});
      prior_sd_site_diameter_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 56;
      prior_sd_site_diameter_rate = context__.vals_r("prior_sd_site_diameter_rate")[(1
        - 1)];
      current_statement__ = 56;
      stan::math::check_greater_or_equal(function__,
        "prior_sd_site_diameter_rate", prior_sd_site_diameter_rate, 0);
      current_statement__ = 57;
      context__.validate_dims("data initialization",
        "prior_sd_site_year_rate", "double", std::vector<size_t>{});
      prior_sd_site_year_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 57;
      prior_sd_site_year_rate = context__.vals_r("prior_sd_site_year_rate")[(1
        - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__,
        "prior_sd_site_year_rate", prior_sd_site_year_rate, 0);
      current_statement__ = 58;
      context__.validate_dims("data initialization",
        "prior_sd_residual_rate", "double", std::vector<size_t>{});
      prior_sd_residual_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 58;
      prior_sd_residual_rate = context__.vals_r("prior_sd_residual_rate")[(1
        - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__,
        "prior_sd_residual_rate", prior_sd_residual_rate, 0);
      current_statement__ = 59;
      context__.validate_dims("data initialization", "prior_only", "int",
        std::vector<size_t>{});
      prior_only = std::numeric_limits<int>::min();
      current_statement__ = 59;
      prior_only = context__.vals_i("prior_only")[(1 - 1)];
      current_statement__ = 59;
      stan::math::check_greater_or_equal(function__, "prior_only",
        prior_only, 0);
      current_statement__ = 59;
      stan::math::check_less_or_equal(function__, "prior_only", prior_only, 1);
      current_statement__ = 60;
      nu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 60;
      nu = 4.0;
      current_statement__ = 61;
      log_diameter_ref = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 61;
      log_diameter_ref = stan::math::log(30);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("log_diameter", "nObs", nObs);
      current_statement__ = 63;
      log_diameter_data__ = Eigen::Matrix<double,-1,1>::Constant(nObs,
                              std::numeric_limits<double>::quiet_NaN());
      new (&log_diameter)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(log_diameter_data__.data(),
        nObs);
      current_statement__ = 63;
      stan::model::assign(log_diameter,
        stan::math::subtract(stan::math::log(diameter), log_diameter_ref),
        "assigning variable log_diameter");
      current_statement__ = 64;
      stan::math::validate_non_negative_index("log_weight", "nObs", nObs);
      current_statement__ = 65;
      log_weight_data__ = Eigen::Matrix<double,-1,1>::Constant(nObs,
                            std::numeric_limits<double>::quiet_NaN());
      new (&log_weight)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(log_weight_data__.data(),
        nObs);
      current_statement__ = 65;
      stan::model::assign(log_weight, stan::math::log(weight),
        "assigning variable log_weight");
      current_statement__ = 66;
      stan::math::validate_non_negative_index("z_bSite", "nSite", nSite);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("z_bSiteDiameter", "nSite",
        nSite);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("z_bSiteYear", "nSite", nSite);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("z_bSiteYear", "nYear", nYear);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("bSite", "nSite", nSite);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("bSiteDiameter", "nSite", nSite);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("bSiteYear", "nSite", nSite);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("bSiteYear", "nYear", nYear);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("log_eWeight", "nObs", nObs);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("typical", "nObs", nObs);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("marginal", "nObs", nObs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + nSite + nSite + (nSite *
      nYear);
  }
  inline std::string model_name() const final {
    return "model_weight";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.39.0-15-geec8928",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_weight_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto bWeight30 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto bDiameter = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto bDiameter2 = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto sSite =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto sSiteDiameter =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 6;
      auto sSiteYear =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 7;
      auto sWeight =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 8;
      auto z_bSite =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite);
      current_statement__ = 9;
      auto z_bSiteDiameter =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite);
      current_statement__ = 10;
      auto z_bSiteYear =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(nSite,
          nYear);
      Eigen::Matrix<local_scalar_t__,-1,1> bSite =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(bSite, stan::math::multiply(z_bSite, sSite),
        "assigning variable bSite");
      Eigen::Matrix<local_scalar_t__,-1,1> bSiteDiameter =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(bSiteDiameter,
        stan::math::multiply(z_bSiteDiameter, sSiteDiameter),
        "assigning variable bSiteDiameter");
      Eigen::Matrix<local_scalar_t__,-1,-1> bSiteYear =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nSite, nYear,
          DUMMY_VAR__);
      current_statement__ = 13;
      stan::model::assign(bSiteYear,
        stan::math::multiply(z_bSiteYear, sSiteYear),
        "assigning variable bSiteYear");
      Eigen::Matrix<local_scalar_t__,-1,1> log_eWeight =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nObs, DUMMY_VAR__);
      current_statement__ = 19;
      for (int i = 1; i <= nObs; ++i) {
        current_statement__ = 17;
        stan::model::assign(log_eWeight, ((((bWeight30 +
          stan::model::rvalue(bSite, "bSite",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i)))))
          + ((bDiameter +
          stan::model::rvalue(bSiteDiameter, "bSiteDiameter",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i)))))
          *
          stan::model::rvalue(log_diameter, "log_diameter",
            stan::model::index_uni(i)))) + (bDiameter2 *
          stan::math::pow(
            stan::model::rvalue(log_diameter, "log_diameter",
              stan::model::index_uni(i)), 2))) +
          stan::model::rvalue(bSiteYear, "bSiteYear",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i))),
            stan::model::index_uni(
              stan::model::rvalue(year, "year", stan::model::index_uni(i))))),
          "assigning variable log_eWeight", stan::model::index_uni(i));
      }
      {
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(bWeight30,
                         prior_intercept_mu, prior_intercept_sd));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(bDiameter,
                         prior_diameter_mu, prior_diameter_sd));
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(bDiameter2,
                         prior_diameter2_mu, prior_diameter2_sd));
        current_statement__ = 28;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sSite,
                         prior_sd_site_rate));
        current_statement__ = 29;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sSiteDiameter,
                         prior_sd_site_diameter_rate));
        current_statement__ = 30;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sSiteYear,
                         prior_sd_site_year_rate));
        current_statement__ = 31;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sWeight,
                         prior_sd_residual_rate));
        current_statement__ = 32;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z_bSite));
        current_statement__ = 33;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z_bSiteDiameter));
        current_statement__ = 34;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(z_bSiteYear)));
        current_statement__ = 37;
        if (stan::math::logical_eq(prior_only, 0)) {
          current_statement__ = 35;
          lp_accum__.add(stan::math::student_t_lpdf<propto__>(log_weight, nu,
                           log_eWeight, sWeight));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_weight_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto bWeight30 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto bDiameter = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto bDiameter2 = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto sSite =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto sSiteDiameter =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 6;
      auto sSiteYear =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 7;
      auto sWeight =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 8;
      auto z_bSite =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite);
      current_statement__ = 9;
      auto z_bSiteDiameter =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite);
      current_statement__ = 10;
      auto z_bSiteYear =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(nSite,
          nYear);
      Eigen::Matrix<local_scalar_t__,-1,1> bSite =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(bSite, stan::math::multiply(z_bSite, sSite),
        "assigning variable bSite");
      Eigen::Matrix<local_scalar_t__,-1,1> bSiteDiameter =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(bSiteDiameter,
        stan::math::multiply(z_bSiteDiameter, sSiteDiameter),
        "assigning variable bSiteDiameter");
      Eigen::Matrix<local_scalar_t__,-1,-1> bSiteYear =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nSite, nYear,
          DUMMY_VAR__);
      current_statement__ = 13;
      stan::model::assign(bSiteYear,
        stan::math::multiply(z_bSiteYear, sSiteYear),
        "assigning variable bSiteYear");
      Eigen::Matrix<local_scalar_t__,-1,1> log_eWeight =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nObs, DUMMY_VAR__);
      current_statement__ = 19;
      for (int i = 1; i <= nObs; ++i) {
        current_statement__ = 17;
        stan::model::assign(log_eWeight, ((((bWeight30 +
          stan::model::rvalue(bSite, "bSite",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i)))))
          + ((bDiameter +
          stan::model::rvalue(bSiteDiameter, "bSiteDiameter",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i)))))
          *
          stan::model::rvalue(log_diameter, "log_diameter",
            stan::model::index_uni(i)))) + (bDiameter2 *
          stan::math::pow(
            stan::model::rvalue(log_diameter, "log_diameter",
              stan::model::index_uni(i)), 2))) +
          stan::model::rvalue(bSiteYear, "bSiteYear",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i))),
            stan::model::index_uni(
              stan::model::rvalue(year, "year", stan::model::index_uni(i))))),
          "assigning variable log_eWeight", stan::model::index_uni(i));
      }
      {
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(bWeight30,
                         prior_intercept_mu, prior_intercept_sd));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(bDiameter,
                         prior_diameter_mu, prior_diameter_sd));
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(bDiameter2,
                         prior_diameter2_mu, prior_diameter2_sd));
        current_statement__ = 28;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sSite,
                         prior_sd_site_rate));
        current_statement__ = 29;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sSiteDiameter,
                         prior_sd_site_diameter_rate));
        current_statement__ = 30;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sSiteYear,
                         prior_sd_site_year_rate));
        current_statement__ = 31;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sWeight,
                         prior_sd_residual_rate));
        current_statement__ = 32;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z_bSite));
        current_statement__ = 33;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z_bSiteDiameter));
        current_statement__ = 34;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(z_bSiteYear)));
        current_statement__ = 37;
        if (stan::math::logical_eq(prior_only, 0)) {
          current_statement__ = 35;
          lp_accum__.add(stan::math::student_t_lpdf<propto__>(log_weight, nu,
                           log_eWeight, sWeight));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_weight_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto bWeight30 = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto bDiameter = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto bDiameter2 = in__.template read<local_scalar_t__>();
      current_statement__ = 4;
      auto sSite =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto sSiteDiameter =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 6;
      auto sSiteYear =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 7;
      auto sWeight =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 8;
      auto z_bSite =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite);
      current_statement__ = 9;
      auto z_bSiteDiameter =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite);
      current_statement__ = 10;
      auto z_bSiteYear =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(nSite,
          nYear);
      Eigen::Matrix<double,-1,1> bSite =
        Eigen::Matrix<double,-1,1>::Constant(nSite,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> bSiteDiameter =
        Eigen::Matrix<double,-1,1>::Constant(nSite,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> bSiteYear =
        Eigen::Matrix<double,-1,-1>::Constant(nSite, nYear,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> log_eWeight =
        Eigen::Matrix<double,-1,1>::Constant(nObs,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(bWeight30);
      out__.write(bDiameter);
      out__.write(bDiameter2);
      out__.write(sSite);
      out__.write(sSiteDiameter);
      out__.write(sSiteYear);
      out__.write(sWeight);
      out__.write(z_bSite);
      out__.write(z_bSiteDiameter);
      out__.write(z_bSiteYear);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 11;
      stan::model::assign(bSite, stan::math::multiply(z_bSite, sSite),
        "assigning variable bSite");
      current_statement__ = 12;
      stan::model::assign(bSiteDiameter,
        stan::math::multiply(z_bSiteDiameter, sSiteDiameter),
        "assigning variable bSiteDiameter");
      current_statement__ = 13;
      stan::model::assign(bSiteYear,
        stan::math::multiply(z_bSiteYear, sSiteYear),
        "assigning variable bSiteYear");
      current_statement__ = 19;
      for (int i = 1; i <= nObs; ++i) {
        current_statement__ = 17;
        stan::model::assign(log_eWeight, ((((bWeight30 +
          stan::model::rvalue(bSite, "bSite",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i)))))
          + ((bDiameter +
          stan::model::rvalue(bSiteDiameter, "bSiteDiameter",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i)))))
          *
          stan::model::rvalue(log_diameter, "log_diameter",
            stan::model::index_uni(i)))) + (bDiameter2 *
          stan::math::pow(
            stan::model::rvalue(log_diameter, "log_diameter",
              stan::model::index_uni(i)), 2))) +
          stan::model::rvalue(bSiteYear, "bSiteYear",
            stan::model::index_uni(
              stan::model::rvalue(site, "site", stan::model::index_uni(i))),
            stan::model::index_uni(
              stan::model::rvalue(year, "year", stan::model::index_uni(i))))),
          "assigning variable log_eWeight", stan::model::index_uni(i));
      }
      if (emit_transformed_parameters__) {
        out__.write(bSite);
        out__.write(bSiteDiameter);
        out__.write(bSiteYear);
        out__.write(log_eWeight);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> typical =
        Eigen::Matrix<double,-1,1>::Constant(nObs,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> marginal =
        Eigen::Matrix<double,-1,1>::Constant(nObs,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 24;
      for (int i = 1; i <= nObs; ++i) {
        double lp_typical = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 20;
        lp_typical = ((bWeight30 + (bDiameter *
          stan::model::rvalue(log_diameter, "log_diameter",
            stan::model::index_uni(i))))
          + (bDiameter2 *
          stan::math::pow(
            stan::model::rvalue(log_diameter, "log_diameter",
              stan::model::index_uni(i)), 2)));
        current_statement__ = 21;
        stan::model::assign(typical, stan::math::exp(lp_typical),
          "assigning variable typical", stan::model::index_uni(i));
        current_statement__ = 22;
        stan::model::assign(marginal,
          stan::math::exp(((((bWeight30 +
            stan::math::normal_rng(0, sSite, base_rng__)) + ((bDiameter +
            stan::math::normal_rng(0, sSiteDiameter, base_rng__)) *
            stan::model::rvalue(log_diameter, "log_diameter",
              stan::model::index_uni(i)))) + (bDiameter2 *
            stan::math::pow(
              stan::model::rvalue(log_diameter, "log_diameter",
                stan::model::index_uni(i)), 2))) +
            stan::math::normal_rng(0, sSiteYear, base_rng__))),
          "assigning variable marginal", stan::model::index_uni(i));
      }
      out__.write(typical);
      out__.write(marginal);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ bWeight30 = DUMMY_VAR__;
      current_statement__ = 1;
      bWeight30 = in__.read<local_scalar_t__>();
      out__.write(bWeight30);
      local_scalar_t__ bDiameter = DUMMY_VAR__;
      current_statement__ = 2;
      bDiameter = in__.read<local_scalar_t__>();
      out__.write(bDiameter);
      local_scalar_t__ bDiameter2 = DUMMY_VAR__;
      current_statement__ = 3;
      bDiameter2 = in__.read<local_scalar_t__>();
      out__.write(bDiameter2);
      local_scalar_t__ sSite = DUMMY_VAR__;
      current_statement__ = 4;
      sSite = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sSite);
      local_scalar_t__ sSiteDiameter = DUMMY_VAR__;
      current_statement__ = 5;
      sSiteDiameter = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sSiteDiameter);
      local_scalar_t__ sSiteYear = DUMMY_VAR__;
      current_statement__ = 6;
      sSiteYear = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sSiteYear);
      local_scalar_t__ sWeight = DUMMY_VAR__;
      current_statement__ = 7;
      sWeight = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sWeight);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bSite =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(z_bSite,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite),
        "assigning variable z_bSite");
      out__.write(z_bSite);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bSiteDiameter =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(z_bSiteDiameter,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite),
        "assigning variable z_bSiteDiameter");
      out__.write(z_bSiteDiameter);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_bSiteYear =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nSite, nYear,
          DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(z_bSiteYear,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(nSite, nYear),
        "assigning variable z_bSiteYear");
      out__.write(z_bSiteYear);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "bWeight30",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "bDiameter",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "bDiameter2",
        "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sSite", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sSiteDiameter",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "sSiteYear",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "sWeight",
        "double", std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "z_bSite",
        "double", std::vector<size_t>{static_cast<size_t>(nSite)});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "z_bSiteDiameter",
        "double", std::vector<size_t>{static_cast<size_t>(nSite)});
      current_statement__ = 10;
      context__.validate_dims("parameter initialization", "z_bSiteYear",
        "double",
        std::vector<size_t>{static_cast<size_t>(nSite),
          static_cast<size_t>(nYear)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ bWeight30 = DUMMY_VAR__;
      current_statement__ = 1;
      bWeight30 = context__.vals_r("bWeight30")[(1 - 1)];
      out__.write(bWeight30);
      local_scalar_t__ bDiameter = DUMMY_VAR__;
      current_statement__ = 2;
      bDiameter = context__.vals_r("bDiameter")[(1 - 1)];
      out__.write(bDiameter);
      local_scalar_t__ bDiameter2 = DUMMY_VAR__;
      current_statement__ = 3;
      bDiameter2 = context__.vals_r("bDiameter2")[(1 - 1)];
      out__.write(bDiameter2);
      local_scalar_t__ sSite = DUMMY_VAR__;
      current_statement__ = 4;
      sSite = context__.vals_r("sSite")[(1 - 1)];
      out__.write_free_lb(0, sSite);
      local_scalar_t__ sSiteDiameter = DUMMY_VAR__;
      current_statement__ = 5;
      sSiteDiameter = context__.vals_r("sSiteDiameter")[(1 - 1)];
      out__.write_free_lb(0, sSiteDiameter);
      local_scalar_t__ sSiteYear = DUMMY_VAR__;
      current_statement__ = 6;
      sSiteYear = context__.vals_r("sSiteYear")[(1 - 1)];
      out__.write_free_lb(0, sSiteYear);
      local_scalar_t__ sWeight = DUMMY_VAR__;
      current_statement__ = 7;
      sWeight = context__.vals_r("sWeight")[(1 - 1)];
      out__.write_free_lb(0, sWeight);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bSite =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_bSite_flat__;
        current_statement__ = 8;
        z_bSite_flat__ = context__.vals_r("z_bSite");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
          stan::model::assign(z_bSite, z_bSite_flat__[(pos__ - 1)],
            "assigning variable z_bSite", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z_bSite);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bSiteDiameter =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_bSiteDiameter_flat__;
        current_statement__ = 9;
        z_bSiteDiameter_flat__ = context__.vals_r("z_bSiteDiameter");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
          stan::model::assign(z_bSiteDiameter, z_bSiteDiameter_flat__[(pos__
            - 1)], "assigning variable z_bSiteDiameter",
            stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z_bSiteDiameter);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_bSiteYear =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nSite, nYear,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_bSiteYear_flat__;
        current_statement__ = 10;
        z_bSiteYear_flat__ = context__.vals_r("z_bSiteYear");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
            stan::model::assign(z_bSiteYear, z_bSiteYear_flat__[(pos__ - 1)],
              "assigning variable z_bSiteYear",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(z_bSiteYear);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"bWeight30", "bDiameter",
                "bDiameter2", "sSite", "sSiteDiameter", "sSiteYear",
                "sWeight", "z_bSite", "z_bSiteDiameter", "z_bSiteYear"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"bSite", "bSiteDiameter", "bSiteYear", "log_eWeight"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"typical", "marginal"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(nSite)},
                std::vector<size_t>{static_cast<size_t>(nSite)},
                std::vector<size_t>{static_cast<size_t>(nSite),
                  static_cast<size_t>(nYear)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(nSite)},
             std::vector<size_t>{static_cast<size_t>(nSite)},
             std::vector<size_t>{static_cast<size_t>(nSite),
               static_cast<size_t>(nYear)},
             std::vector<size_t>{static_cast<size_t>(nObs)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(nObs)},
             std::vector<size_t>{static_cast<size_t>(nObs)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "bWeight30");
    param_names__.emplace_back(std::string() + "bDiameter");
    param_names__.emplace_back(std::string() + "bDiameter2");
    param_names__.emplace_back(std::string() + "sSite");
    param_names__.emplace_back(std::string() + "sSiteDiameter");
    param_names__.emplace_back(std::string() + "sSiteYear");
    param_names__.emplace_back(std::string() + "sWeight");
    for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_bSite" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_bSiteDiameter" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
        param_names__.emplace_back(std::string() + "z_bSiteYear" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
        param_names__.emplace_back(std::string() + "bSite" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
        param_names__.emplace_back(std::string() + "bSiteDiameter" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
          param_names__.emplace_back(std::string() + "bSiteYear" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_eWeight" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
        param_names__.emplace_back(std::string() + "typical" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
        param_names__.emplace_back(std::string() + "marginal" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "bWeight30");
    param_names__.emplace_back(std::string() + "bDiameter");
    param_names__.emplace_back(std::string() + "bDiameter2");
    param_names__.emplace_back(std::string() + "sSite");
    param_names__.emplace_back(std::string() + "sSiteDiameter");
    param_names__.emplace_back(std::string() + "sSiteYear");
    param_names__.emplace_back(std::string() + "sWeight");
    for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_bSite" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_bSiteDiameter" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
        param_names__.emplace_back(std::string() + "z_bSiteYear" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
        param_names__.emplace_back(std::string() + "bSite" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
        param_names__.emplace_back(std::string() + "bSiteDiameter" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
          param_names__.emplace_back(std::string() + "bSiteYear" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_eWeight" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
        param_names__.emplace_back(std::string() + "typical" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
        param_names__.emplace_back(std::string() + "marginal" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"bWeight30\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bDiameter\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bDiameter2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSite\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSiteDiameter\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSiteYear\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sWeight\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_bSite\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"parameters\"},{\"name\":\"z_bSiteDiameter\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"parameters\"},{\"name\":\"z_bSiteYear\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nSite) + ",\"cols\":" + std::to_string(nYear) + "},\"block\":\"parameters\"},{\"name\":\"bSite\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"transformed_parameters\"},{\"name\":\"bSiteDiameter\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"transformed_parameters\"},{\"name\":\"bSiteYear\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nSite) + ",\"cols\":" + std::to_string(nYear) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_eWeight\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nObs) + "},\"block\":\"transformed_parameters\"},{\"name\":\"typical\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nObs) + "},\"block\":\"generated_quantities\"},{\"name\":\"marginal\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nObs) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"bWeight30\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bDiameter\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bDiameter2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSite\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSiteDiameter\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSiteYear\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sWeight\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_bSite\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"parameters\"},{\"name\":\"z_bSiteDiameter\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"parameters\"},{\"name\":\"z_bSiteYear\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nSite) + ",\"cols\":" + std::to_string(nYear) + "},\"block\":\"parameters\"},{\"name\":\"bSite\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"transformed_parameters\"},{\"name\":\"bSiteDiameter\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"transformed_parameters\"},{\"name\":\"bSiteYear\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nSite) + ",\"cols\":" + std::to_string(nYear) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_eWeight\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nObs) + "},\"block\":\"transformed_parameters\"},{\"name\":\"typical\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nObs) + "},\"block\":\"generated_quantities\"},{\"name\":\"marginal\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nObs) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + nSite + nSite +
      (nSite * nYear);
    const size_t num_transformed = emit_transformed_parameters * (nSite +
      nSite + (nSite * nYear) + nObs);
    const size_t num_gen_quantities = emit_generated_quantities * (nObs +
      nObs);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1 + 1 + 1 + 1 + 1 + 1 + nSite + nSite +
      (nSite * nYear);
    const size_t num_transformed = emit_transformed_parameters * (nSite +
      nSite + (nSite * nYear) + nObs);
    const size_t num_gen_quantities = emit_generated_quantities * (nObs +
      nObs);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_weight_namespace::model_weight;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_weight_namespace::profiles__;
}
#endif
#endif
