// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.39.0
#include <stan/model/model_header.hpp>
namespace model_carbon_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 16> locations_array__ =
  {" (found before start of program)",
  " (in 'carbon', line 22, column 2 to column 17)",
  " (in 'carbon', line 23, column 2 to column 26)",
  " (in 'carbon', line 26, column 2 to column 63)",
  " (in 'carbon', line 27, column 2 to column 48)",
  " (in 'carbon', line 29, column 4 to column 35)",
  " (in 'carbon', line 30, column 4 to column 65)",
  " (in 'carbon', line 28, column 23 to line 31, column 3)",
  " (in 'carbon', line 28, column 2 to line 31, column 3)",
  " (in 'carbon', line 13, column 2 to column 21)",
  " (in 'carbon', line 14, column 27 to column 32)",
  " (in 'carbon', line 14, column 2 to column 50)",
  " (in 'carbon', line 16, column 2 to column 28)",
  " (in 'carbon', line 17, column 2 to column 35)",
  " (in 'carbon', line 18, column 2 to column 37)",
  " (in 'carbon', line 19, column 2 to column 35)"};
#include <stan_meta_header.hpp>
class model_carbon final : public model_base_crtp<model_carbon> {
private:
  int n_obs;
  Eigen::Matrix<double,-1,1> carbon_fraction_data__;
  double prior_intercept_mean;
  double prior_intercept_sd;
  double prior_precision_rate;
  int prior_only;
  Eigen::Map<Eigen::Matrix<double,-1,1>> carbon_fraction{nullptr, 0};
public:
  ~model_carbon() {}
  model_carbon(stan::io::var_context& context__, unsigned int
               random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_carbon_namespace::model_carbon";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 9;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{});
      n_obs = std::numeric_limits<int>::min();
      current_statement__ = 9;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "n_obs", n_obs, 0);
      current_statement__ = 10;
      stan::math::validate_non_negative_index("carbon_fraction", "n_obs",
        n_obs);
      current_statement__ = 11;
      context__.validate_dims("data initialization", "carbon_fraction",
        "double", std::vector<size_t>{static_cast<size_t>(n_obs)});
      carbon_fraction_data__ = Eigen::Matrix<double,-1,1>::Constant(n_obs,
                                 std::numeric_limits<double>::quiet_NaN());
      new (&carbon_fraction)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(carbon_fraction_data__.data(),
        n_obs);
      {
        std::vector<local_scalar_t__> carbon_fraction_flat__;
        current_statement__ = 11;
        carbon_fraction_flat__ = context__.vals_r("carbon_fraction");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
          stan::model::assign(carbon_fraction, carbon_fraction_flat__[(pos__
            - 1)], "assigning variable carbon_fraction",
            stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "carbon_fraction",
        carbon_fraction, 0);
      current_statement__ = 11;
      stan::math::check_less_or_equal(function__, "carbon_fraction",
        carbon_fraction, 1);
      current_statement__ = 12;
      context__.validate_dims("data initialization", "prior_intercept_mean",
        "double", std::vector<size_t>{});
      prior_intercept_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      prior_intercept_mean = context__.vals_r("prior_intercept_mean")[(1 -
        1)];
      current_statement__ = 13;
      context__.validate_dims("data initialization", "prior_intercept_sd",
        "double", std::vector<size_t>{});
      prior_intercept_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 13;
      prior_intercept_sd = context__.vals_r("prior_intercept_sd")[(1 - 1)];
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "prior_intercept_sd",
        prior_intercept_sd, 0);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "prior_precision_rate",
        "double", std::vector<size_t>{});
      prior_precision_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 14;
      prior_precision_rate = context__.vals_r("prior_precision_rate")[(1 -
        1)];
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "prior_precision_rate",
        prior_precision_rate, 0);
      current_statement__ = 15;
      context__.validate_dims("data initialization", "prior_only", "int",
        std::vector<size_t>{});
      prior_only = std::numeric_limits<int>::min();
      current_statement__ = 15;
      prior_only = context__.vals_i("prior_only")[(1 - 1)];
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "prior_only",
        prior_only, 0);
      current_statement__ = 15;
      stan::math::check_less_or_equal(function__, "prior_only", prior_only, 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_carbon";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.39.0",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_carbon_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto intercept = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto precision =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      {
        current_statement__ = 3;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(intercept,
                         prior_intercept_mean, prior_intercept_sd));
        current_statement__ = 4;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(precision,
                         prior_precision_rate));
        current_statement__ = 8;
        if (stan::math::logical_eq(prior_only, 0)) {
          local_scalar_t__ mu = DUMMY_VAR__;
          current_statement__ = 5;
          mu = stan::math::inv_logit(intercept);
          current_statement__ = 6;
          lp_accum__.add(stan::math::beta_lpdf<propto__>(carbon_fraction, (mu
                           * precision), ((1 - mu) * precision)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_carbon_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto intercept = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto precision =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      {
        current_statement__ = 3;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(intercept,
                         prior_intercept_mean, prior_intercept_sd));
        current_statement__ = 4;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(precision,
                         prior_precision_rate));
        current_statement__ = 8;
        if (stan::math::logical_eq(prior_only, 0)) {
          local_scalar_t__ mu = DUMMY_VAR__;
          current_statement__ = 5;
          mu = stan::math::inv_logit(intercept);
          current_statement__ = 6;
          lp_accum__.add(stan::math::beta_lpdf<propto__>(carbon_fraction, (mu
                           * precision), ((1 - mu) * precision)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_carbon_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto intercept = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto precision =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      out__.write(intercept);
      out__.write(precision);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ intercept = DUMMY_VAR__;
      current_statement__ = 1;
      intercept = in__.read<local_scalar_t__>();
      out__.write(intercept);
      local_scalar_t__ precision = DUMMY_VAR__;
      current_statement__ = 2;
      precision = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, precision);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "intercept",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "precision",
        "double", std::vector<size_t>{});
      local_scalar_t__ intercept = DUMMY_VAR__;
      current_statement__ = 1;
      intercept = context__.vals_r("intercept")[(1 - 1)];
      out__.write(intercept);
      local_scalar_t__ precision = DUMMY_VAR__;
      current_statement__ = 2;
      precision = context__.vals_r("precision")[(1 - 1)];
      out__.write_free_lb(0, precision);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"intercept", "precision"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "intercept");
    param_names__.emplace_back(std::string() + "precision");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "intercept");
    param_names__.emplace_back(std::string() + "precision");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"intercept\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"precision\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"intercept\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"precision\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1;
    const size_t num_transformed = emit_transformed_parameters * (0U);
    const size_t num_gen_quantities = emit_generated_quantities * (0U);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1;
    const size_t num_transformed = emit_transformed_parameters * (0U);
    const size_t num_gen_quantities = emit_generated_quantities * (0U);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_carbon_namespace::model_carbon;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_carbon_namespace::profiles__;
}
#endif
#endif
