// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_weight_macro_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 66> locations_array__ =
  {" (found before start of program)",
  " (in 'weight_macro', line 41, column 2 to column 15)",
  " (in 'weight_macro', line 42, column 2 to column 15)",
  " (in 'weight_macro', line 43, column 2 to column 22)",
  " (in 'weight_macro', line 44, column 2 to column 22)",
  " (in 'weight_macro', line 45, column 2 to column 22)",
  " (in 'weight_macro', line 46, column 2 to column 26)",
  " (in 'weight_macro', line 47, column 2 to column 24)",
  " (in 'weight_macro', line 48, column 2 to column 24)",
  " (in 'weight_macro', line 49, column 2 to column 35)",
  " (in 'weight_macro', line 52, column 2 to column 40)",
  " (in 'weight_macro', line 53, column 2 to column 40)",
  " (in 'weight_macro', line 54, column 2 to column 59)",
  " (in 'weight_macro', line 57, column 2 to column 59)",
  " (in 'weight_macro', line 58, column 2 to column 53)",
  " (in 'weight_macro', line 59, column 2 to column 40)",
  " (in 'weight_macro', line 60, column 2 to column 42)",
  " (in 'weight_macro', line 61, column 2 to column 42)",
  " (in 'weight_macro', line 62, column 2 to column 51)",
  " (in 'weight_macro', line 63, column 2 to column 25)",
  " (in 'weight_macro', line 64, column 2 to column 25)",
  " (in 'weight_macro', line 65, column 2 to column 40)",
  " (in 'weight_macro', line 70, column 11 to column 15)",
  " (in 'weight_macro', line 70, column 4 to column 29)",
  " (in 'weight_macro', line 72, column 6 to line 75, column 53)",
  " (in 'weight_macro', line 71, column 22 to line 76, column 5)",
  " (in 'weight_macro', line 71, column 4 to line 76, column 5)",
  " (in 'weight_macro', line 78, column 6 to column 48)",
  " (in 'weight_macro', line 79, column 6 to column 39)",
  " (in 'weight_macro', line 77, column 22 to line 80, column 5)",
  " (in 'weight_macro', line 77, column 4 to line 80, column 5)",
  " (in 'weight_macro', line 66, column 23 to line 81, column 3)",
  " (in 'weight_macro', line 66, column 2 to line 81, column 3)",
  " (in 'weight_macro', line 16, column 2 to column 20)",
  " (in 'weight_macro', line 17, column 2 to column 21)",
  " (in 'weight_macro', line 18, column 2 to column 21)",
  " (in 'weight_macro', line 19, column 8 to column 12)",
  " (in 'weight_macro', line 19, column 2 to column 45)",
  " (in 'weight_macro', line 20, column 8 to column 12)",
  " (in 'weight_macro', line 20, column 2 to column 45)",
  " (in 'weight_macro', line 21, column 18 to column 22)",
  " (in 'weight_macro', line 21, column 2 to column 31)",
  " (in 'weight_macro', line 22, column 18 to column 22)",
  " (in 'weight_macro', line 22, column 2 to column 31)",
  " (in 'weight_macro', line 23, column 2 to column 27)",
  " (in 'weight_macro', line 25, column 2 to column 26)",
  " (in 'weight_macro', line 26, column 2 to column 35)",
  " (in 'weight_macro', line 27, column 2 to column 23)",
  " (in 'weight_macro', line 28, column 2 to column 32)",
  " (in 'weight_macro', line 29, column 2 to column 33)",
  " (in 'weight_macro', line 30, column 2 to column 35)",
  " (in 'weight_macro', line 31, column 2 to column 35)",
  " (in 'weight_macro', line 32, column 2 to column 40)",
  " (in 'weight_macro', line 33, column 2 to column 35)",
  " (in 'weight_macro', line 34, column 2 to column 37)",
  " (in 'weight_macro', line 37, column 2 to column 40)",
  " (in 'weight_macro', line 38, column 9 to column 13)",
  " (in 'weight_macro', line 38, column 2 to column 57)",
  " (in 'weight_macro', line 47, column 9 to column 14)",
  " (in 'weight_macro', line 48, column 9 to column 14)",
  " (in 'weight_macro', line 49, column 9 to column 14)",
  " (in 'weight_macro', line 49, column 16 to column 21)",
  " (in 'weight_macro', line 52, column 9 to column 14)",
  " (in 'weight_macro', line 53, column 9 to column 14)",
  " (in 'weight_macro', line 54, column 9 to column 14)",
  " (in 'weight_macro', line 54, column 16 to column 21)"};
#include <stan_meta_header.hpp>
class model_weight_macro final : public model_base_crtp<model_weight_macro> {
private:
  int nObs;
  int nSite;
  int nYear;
  std::vector<int> site;
  std::vector<int> year;
  Eigen::Matrix<double,-1,1> fronds_data__;
  Eigen::Matrix<double,-1,1> weight_data__;
  double fronds_ref;
  double prior_intercept_mu;
  double prior_intercept_sd;
  double prior_fronds_mu;
  double prior_fronds_sd;
  double prior_shape_rate;
  double prior_sd_site_rate;
  double prior_sd_year_rate;
  double prior_sd_site_year_rate;
  int prior_only;
  int site_year_on;
  double log_fronds_ref;
  Eigen::Matrix<double,-1,1> log_fronds_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> fronds{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> weight{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> log_fronds{nullptr, 0};
public:
  ~model_weight_macro() {}
  model_weight_macro(stan::io::var_context& context__, unsigned int
                     random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_weight_macro_namespace::model_weight_macro";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 33;
      context__.validate_dims("data initialization", "nObs", "int",
        std::vector<size_t>{});
      nObs = std::numeric_limits<int>::min();
      current_statement__ = 33;
      nObs = context__.vals_i("nObs")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "nObs", nObs, 0);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "nSite", "int",
        std::vector<size_t>{});
      nSite = std::numeric_limits<int>::min();
      current_statement__ = 34;
      nSite = context__.vals_i("nSite")[(1 - 1)];
      current_statement__ = 34;
      stan::math::check_greater_or_equal(function__, "nSite", nSite, 1);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "nYear", "int",
        std::vector<size_t>{});
      nYear = std::numeric_limits<int>::min();
      current_statement__ = 35;
      nYear = context__.vals_i("nYear")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "nYear", nYear, 1);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("site", "nObs", nObs);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "site", "int",
        std::vector<size_t>{static_cast<size_t>(nObs)});
      site = std::vector<int>(nObs, std::numeric_limits<int>::min());
      current_statement__ = 37;
      site = context__.vals_i("site");
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "site", site, 1);
      current_statement__ = 37;
      stan::math::check_less_or_equal(function__, "site", site, nSite);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("year", "nObs", nObs);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "year", "int",
        std::vector<size_t>{static_cast<size_t>(nObs)});
      year = std::vector<int>(nObs, std::numeric_limits<int>::min());
      current_statement__ = 39;
      year = context__.vals_i("year");
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "year", year, 1);
      current_statement__ = 39;
      stan::math::check_less_or_equal(function__, "year", year, nYear);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("fronds", "nObs", nObs);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "fronds", "double",
        std::vector<size_t>{static_cast<size_t>(nObs)});
      fronds_data__ = Eigen::Matrix<double,-1,1>::Constant(nObs,
                        std::numeric_limits<double>::quiet_NaN());
      new (&fronds)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(fronds_data__.data(), nObs);
      {
        std::vector<local_scalar_t__> fronds_flat__;
        current_statement__ = 41;
        fronds_flat__ = context__.vals_r("fronds");
        current_statement__ = 41;
        pos__ = 1;
        current_statement__ = 41;
        for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
          current_statement__ = 41;
          stan::model::assign(fronds, fronds_flat__[(pos__ - 1)],
            "assigning variable fronds", stan::model::index_uni(sym1__));
          current_statement__ = 41;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "fronds", fronds, 0);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("weight", "nObs", nObs);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "weight", "double",
        std::vector<size_t>{static_cast<size_t>(nObs)});
      weight_data__ = Eigen::Matrix<double,-1,1>::Constant(nObs,
                        std::numeric_limits<double>::quiet_NaN());
      new (&weight)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(weight_data__.data(), nObs);
      {
        std::vector<local_scalar_t__> weight_flat__;
        current_statement__ = 43;
        weight_flat__ = context__.vals_r("weight");
        current_statement__ = 43;
        pos__ = 1;
        current_statement__ = 43;
        for (int sym1__ = 1; sym1__ <= nObs; ++sym1__) {
          current_statement__ = 43;
          stan::model::assign(weight, weight_flat__[(pos__ - 1)],
            "assigning variable weight", stan::model::index_uni(sym1__));
          current_statement__ = 43;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "weight", weight, 0);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "fronds_ref", "double",
        std::vector<size_t>{});
      fronds_ref = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 44;
      fronds_ref = context__.vals_r("fronds_ref")[(1 - 1)];
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "fronds_ref",
        fronds_ref, 0);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "prior_intercept_mu",
        "double", std::vector<size_t>{});
      prior_intercept_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 45;
      prior_intercept_mu = context__.vals_r("prior_intercept_mu")[(1 - 1)];
      current_statement__ = 46;
      context__.validate_dims("data initialization", "prior_intercept_sd",
        "double", std::vector<size_t>{});
      prior_intercept_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 46;
      prior_intercept_sd = context__.vals_r("prior_intercept_sd")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "prior_intercept_sd",
        prior_intercept_sd, 0);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "prior_fronds_mu",
        "double", std::vector<size_t>{});
      prior_fronds_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 47;
      prior_fronds_mu = context__.vals_r("prior_fronds_mu")[(1 - 1)];
      current_statement__ = 48;
      context__.validate_dims("data initialization", "prior_fronds_sd",
        "double", std::vector<size_t>{});
      prior_fronds_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 48;
      prior_fronds_sd = context__.vals_r("prior_fronds_sd")[(1 - 1)];
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "prior_fronds_sd",
        prior_fronds_sd, 0);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "prior_shape_rate",
        "double", std::vector<size_t>{});
      prior_shape_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      prior_shape_rate = context__.vals_r("prior_shape_rate")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "prior_shape_rate",
        prior_shape_rate, 0);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "prior_sd_site_rate",
        "double", std::vector<size_t>{});
      prior_sd_site_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 50;
      prior_sd_site_rate = context__.vals_r("prior_sd_site_rate")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "prior_sd_site_rate",
        prior_sd_site_rate, 0);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "prior_sd_year_rate",
        "double", std::vector<size_t>{});
      prior_sd_year_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 51;
      prior_sd_year_rate = context__.vals_r("prior_sd_year_rate")[(1 - 1)];
      current_statement__ = 51;
      stan::math::check_greater_or_equal(function__, "prior_sd_year_rate",
        prior_sd_year_rate, 0);
      current_statement__ = 52;
      context__.validate_dims("data initialization",
        "prior_sd_site_year_rate", "double", std::vector<size_t>{});
      prior_sd_site_year_rate = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 52;
      prior_sd_site_year_rate = context__.vals_r("prior_sd_site_year_rate")[(1
        - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__,
        "prior_sd_site_year_rate", prior_sd_site_year_rate, 0);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "prior_only", "int",
        std::vector<size_t>{});
      prior_only = std::numeric_limits<int>::min();
      current_statement__ = 53;
      prior_only = context__.vals_i("prior_only")[(1 - 1)];
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "prior_only",
        prior_only, 0);
      current_statement__ = 53;
      stan::math::check_less_or_equal(function__, "prior_only", prior_only, 1);
      current_statement__ = 54;
      context__.validate_dims("data initialization", "site_year_on", "int",
        std::vector<size_t>{});
      site_year_on = std::numeric_limits<int>::min();
      current_statement__ = 54;
      site_year_on = context__.vals_i("site_year_on")[(1 - 1)];
      current_statement__ = 54;
      stan::math::check_greater_or_equal(function__, "site_year_on",
        site_year_on, 0);
      current_statement__ = 54;
      stan::math::check_less_or_equal(function__, "site_year_on",
        site_year_on, 1);
      current_statement__ = 55;
      log_fronds_ref = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 55;
      log_fronds_ref = stan::math::log(fronds_ref);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("log_fronds", "nObs", nObs);
      current_statement__ = 57;
      log_fronds_data__ = Eigen::Matrix<double,-1,1>::Constant(nObs,
                            std::numeric_limits<double>::quiet_NaN());
      new (&log_fronds)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(log_fronds_data__.data(),
        nObs);
      current_statement__ = 57;
      stan::model::assign(log_fronds,
        stan::math::subtract(stan::math::log(fronds), log_fronds_ref),
        "assigning variable log_fronds");
      current_statement__ = 58;
      stan::math::validate_non_negative_index("z_bSite", "nSite", nSite);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("z_bYear", "nYear", nYear);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("z_bSiteYear", "nSite", nSite);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("z_bSiteYear", "nYear", nYear);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("bSite", "nSite", nSite);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("bYear", "nYear", nYear);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("bSiteYear", "nSite", nSite);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("bSiteYear", "nYear", nYear);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + nSite + nYear + (nSite * nYear);
  }
  inline std::string model_name() const final {
    return "model_weight_macro";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_weight_macro_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ bWeight = DUMMY_VAR__;
      current_statement__ = 1;
      bWeight = in__.template read<local_scalar_t__>();
      local_scalar_t__ bFronds = DUMMY_VAR__;
      current_statement__ = 2;
      bFronds = in__.template read<local_scalar_t__>();
      local_scalar_t__ shape = DUMMY_VAR__;
      current_statement__ = 3;
      shape = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ sSite = DUMMY_VAR__;
      current_statement__ = 4;
      sSite = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ sYear = DUMMY_VAR__;
      current_statement__ = 5;
      sYear = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ sSiteYear = DUMMY_VAR__;
      current_statement__ = 6;
      sSiteYear = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bSite =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 7;
      z_bSite = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(nSite);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bYear =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nYear, DUMMY_VAR__);
      current_statement__ = 8;
      z_bYear = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(nYear);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_bSiteYear =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nSite, nYear,
          DUMMY_VAR__);
      current_statement__ = 9;
      z_bSiteYear = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,-1>>(nSite, nYear);
      Eigen::Matrix<local_scalar_t__,-1,1> bSite =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(bSite, stan::math::multiply(z_bSite, sSite),
        "assigning variable bSite");
      Eigen::Matrix<local_scalar_t__,-1,1> bYear =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nYear, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(bYear, stan::math::multiply(z_bYear, sYear),
        "assigning variable bYear");
      Eigen::Matrix<local_scalar_t__,-1,-1> bSiteYear =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nSite, nYear,
          DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(bSiteYear,
        stan::math::multiply(z_bSiteYear, sSiteYear),
        "assigning variable bSiteYear");
      {
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(bWeight,
                         prior_intercept_mu, prior_intercept_sd));
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(bFronds,
                         prior_fronds_mu, prior_fronds_sd));
        current_statement__ = 15;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(shape,
                         prior_shape_rate));
        current_statement__ = 16;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sSite,
                         prior_sd_site_rate));
        current_statement__ = 17;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sYear,
                         prior_sd_year_rate));
        current_statement__ = 18;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sSiteYear,
                         prior_sd_site_year_rate));
        current_statement__ = 19;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z_bSite));
        current_statement__ = 20;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(z_bYear));
        current_statement__ = 21;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(z_bSiteYear)));
        current_statement__ = 32;
        if (stan::math::logical_eq(prior_only, 0)) {
          current_statement__ = 22;
          stan::math::validate_non_negative_index("log_eWeight", "nObs", nObs);
          Eigen::Matrix<local_scalar_t__,-1,1> log_eWeight =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nObs, DUMMY_VAR__);
          current_statement__ = 26;
          for (int i = 1; i <= nObs; ++i) {
            current_statement__ = 24;
            stan::model::assign(log_eWeight, ((((bWeight +
              stan::model::rvalue(bSite, "bSite",
                stan::model::index_uni(
                  stan::model::rvalue(site, "site", stan::model::index_uni(i)))))
              + (bFronds *
              stan::model::rvalue(log_fronds, "log_fronds",
                stan::model::index_uni(i)))) +
              stan::model::rvalue(bYear, "bYear",
                stan::model::index_uni(
                  stan::model::rvalue(year, "year", stan::model::index_uni(i)))))
              + (site_year_on *
              stan::model::rvalue(bSiteYear, "bSiteYear",
                stan::model::index_uni(
                  stan::model::rvalue(site, "site", stan::model::index_uni(i))),
                stan::model::index_uni(
                  stan::model::rvalue(year, "year", stan::model::index_uni(i)))))),
              "assigning variable log_eWeight", stan::model::index_uni(i));
          }
          current_statement__ = 30;
          for (int i = 1; i <= nObs; ++i) {
            local_scalar_t__ rate_i = DUMMY_VAR__;
            current_statement__ = 27;
            rate_i = (shape /
              stan::math::exp(
                stan::model::rvalue(log_eWeight, "log_eWeight",
                  stan::model::index_uni(i))));
            current_statement__ = 28;
            lp_accum__.add(stan::math::gamma_lpdf<propto__>(
                             stan::model::rvalue(weight, "weight",
                               stan::model::index_uni(i)), shape, rate_i));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_weight_macro_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double bWeight = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      bWeight = in__.template read<local_scalar_t__>();
      double bFronds = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      bFronds = in__.template read<local_scalar_t__>();
      double shape = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      shape = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double sSite = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sSite = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double sYear = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sYear = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double sSiteYear = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      sSiteYear = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> z_bSite =
        Eigen::Matrix<double,-1,1>::Constant(nSite,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      z_bSite = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(nSite);
      Eigen::Matrix<double,-1,1> z_bYear =
        Eigen::Matrix<double,-1,1>::Constant(nYear,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 8;
      z_bYear = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(nYear);
      Eigen::Matrix<double,-1,-1> z_bSiteYear =
        Eigen::Matrix<double,-1,-1>::Constant(nSite, nYear,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 9;
      z_bSiteYear = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,-1>>(nSite, nYear);
      Eigen::Matrix<double,-1,1> bSite =
        Eigen::Matrix<double,-1,1>::Constant(nSite,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> bYear =
        Eigen::Matrix<double,-1,1>::Constant(nYear,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> bSiteYear =
        Eigen::Matrix<double,-1,-1>::Constant(nSite, nYear,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(bWeight);
      out__.write(bFronds);
      out__.write(shape);
      out__.write(sSite);
      out__.write(sYear);
      out__.write(sSiteYear);
      out__.write(z_bSite);
      out__.write(z_bYear);
      out__.write(z_bSiteYear);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 10;
      stan::model::assign(bSite, stan::math::multiply(z_bSite, sSite),
        "assigning variable bSite");
      current_statement__ = 11;
      stan::model::assign(bYear, stan::math::multiply(z_bYear, sYear),
        "assigning variable bYear");
      current_statement__ = 12;
      stan::model::assign(bSiteYear,
        stan::math::multiply(z_bSiteYear, sSiteYear),
        "assigning variable bSiteYear");
      if (emit_transformed_parameters__) {
        out__.write(bSite);
        out__.write(bYear);
        out__.write(bSiteYear);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ bWeight = DUMMY_VAR__;
      current_statement__ = 1;
      bWeight = in__.read<local_scalar_t__>();
      out__.write(bWeight);
      local_scalar_t__ bFronds = DUMMY_VAR__;
      current_statement__ = 2;
      bFronds = in__.read<local_scalar_t__>();
      out__.write(bFronds);
      local_scalar_t__ shape = DUMMY_VAR__;
      current_statement__ = 3;
      shape = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, shape);
      local_scalar_t__ sSite = DUMMY_VAR__;
      current_statement__ = 4;
      sSite = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sSite);
      local_scalar_t__ sYear = DUMMY_VAR__;
      current_statement__ = 5;
      sYear = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sYear);
      local_scalar_t__ sSiteYear = DUMMY_VAR__;
      current_statement__ = 6;
      sSiteYear = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sSiteYear);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bSite =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(z_bSite,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nSite),
        "assigning variable z_bSite");
      out__.write(z_bSite);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bYear =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nYear, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(z_bYear,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nYear),
        "assigning variable z_bYear");
      out__.write(z_bYear);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_bSiteYear =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nSite, nYear,
          DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(z_bSiteYear,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(nSite, nYear),
        "assigning variable z_bSiteYear");
      out__.write(z_bSiteYear);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "bWeight",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "bFronds",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "shape", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sSite", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sYear", "double",
        std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "sSiteYear",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "z_bSite",
        "double", std::vector<size_t>{static_cast<size_t>(nSite)});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "z_bYear",
        "double", std::vector<size_t>{static_cast<size_t>(nYear)});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "z_bSiteYear",
        "double",
        std::vector<size_t>{static_cast<size_t>(nSite),
          static_cast<size_t>(nYear)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ bWeight = DUMMY_VAR__;
      current_statement__ = 1;
      bWeight = context__.vals_r("bWeight")[(1 - 1)];
      out__.write(bWeight);
      local_scalar_t__ bFronds = DUMMY_VAR__;
      current_statement__ = 2;
      bFronds = context__.vals_r("bFronds")[(1 - 1)];
      out__.write(bFronds);
      local_scalar_t__ shape = DUMMY_VAR__;
      current_statement__ = 3;
      shape = context__.vals_r("shape")[(1 - 1)];
      out__.write_free_lb(0, shape);
      local_scalar_t__ sSite = DUMMY_VAR__;
      current_statement__ = 4;
      sSite = context__.vals_r("sSite")[(1 - 1)];
      out__.write_free_lb(0, sSite);
      local_scalar_t__ sYear = DUMMY_VAR__;
      current_statement__ = 5;
      sYear = context__.vals_r("sYear")[(1 - 1)];
      out__.write_free_lb(0, sYear);
      local_scalar_t__ sSiteYear = DUMMY_VAR__;
      current_statement__ = 6;
      sSiteYear = context__.vals_r("sSiteYear")[(1 - 1)];
      out__.write_free_lb(0, sSiteYear);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bSite =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nSite, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_bSite_flat__;
        current_statement__ = 7;
        z_bSite_flat__ = context__.vals_r("z_bSite");
        current_statement__ = 7;
        pos__ = 1;
        current_statement__ = 7;
        for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
          current_statement__ = 7;
          stan::model::assign(z_bSite, z_bSite_flat__[(pos__ - 1)],
            "assigning variable z_bSite", stan::model::index_uni(sym1__));
          current_statement__ = 7;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z_bSite);
      Eigen::Matrix<local_scalar_t__,-1,1> z_bYear =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nYear, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_bYear_flat__;
        current_statement__ = 8;
        z_bYear_flat__ = context__.vals_r("z_bYear");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
          current_statement__ = 8;
          stan::model::assign(z_bYear, z_bYear_flat__[(pos__ - 1)],
            "assigning variable z_bYear", stan::model::index_uni(sym1__));
          current_statement__ = 8;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(z_bYear);
      Eigen::Matrix<local_scalar_t__,-1,-1> z_bSiteYear =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(nSite, nYear,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_bSiteYear_flat__;
        current_statement__ = 9;
        z_bSiteYear_flat__ = context__.vals_r("z_bSiteYear");
        current_statement__ = 9;
        pos__ = 1;
        current_statement__ = 9;
        for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
          current_statement__ = 9;
          for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
            current_statement__ = 9;
            stan::model::assign(z_bSiteYear, z_bSiteYear_flat__[(pos__ - 1)],
              "assigning variable z_bSiteYear",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 9;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(z_bSiteYear);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"bWeight", "bFronds", "shape",
                "sSite", "sYear", "sSiteYear", "z_bSite", "z_bYear",
                "z_bSiteYear"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"bSite", "bYear", "bSiteYear"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(nSite)},
                std::vector<size_t>{static_cast<size_t>(nYear)},
                std::vector<size_t>{static_cast<size_t>(nSite),
                  static_cast<size_t>(nYear)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(nSite)},
             std::vector<size_t>{static_cast<size_t>(nYear)},
             std::vector<size_t>{static_cast<size_t>(nSite),
               static_cast<size_t>(nYear)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "bWeight");
    param_names__.emplace_back(std::string() + "bFronds");
    param_names__.emplace_back(std::string() + "shape");
    param_names__.emplace_back(std::string() + "sSite");
    param_names__.emplace_back(std::string() + "sYear");
    param_names__.emplace_back(std::string() + "sSiteYear");
    for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_bSite" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_bYear" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
        param_names__.emplace_back(std::string() + "z_bSiteYear" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
        param_names__.emplace_back(std::string() + "bSite" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
        param_names__.emplace_back(std::string() + "bYear" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
          param_names__.emplace_back(std::string() + "bSiteYear" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "bWeight");
    param_names__.emplace_back(std::string() + "bFronds");
    param_names__.emplace_back(std::string() + "shape");
    param_names__.emplace_back(std::string() + "sSite");
    param_names__.emplace_back(std::string() + "sYear");
    param_names__.emplace_back(std::string() + "sSiteYear");
    for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_bSite" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
      param_names__.emplace_back(std::string() + "z_bYear" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
        param_names__.emplace_back(std::string() + "z_bSiteYear" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= nSite; ++sym1__) {
        param_names__.emplace_back(std::string() + "bSite" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
        param_names__.emplace_back(std::string() + "bYear" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nYear; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= nSite; ++sym2__) {
          param_names__.emplace_back(std::string() + "bSiteYear" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"bWeight\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bFronds\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"shape\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSite\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sYear\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSiteYear\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_bSite\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"parameters\"},{\"name\":\"z_bYear\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nYear) + "},\"block\":\"parameters\"},{\"name\":\"z_bSiteYear\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nSite) + ",\"cols\":" + std::to_string(nYear) + "},\"block\":\"parameters\"},{\"name\":\"bSite\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"transformed_parameters\"},{\"name\":\"bYear\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nYear) + "},\"block\":\"transformed_parameters\"},{\"name\":\"bSiteYear\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nSite) + ",\"cols\":" + std::to_string(nYear) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"bWeight\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"bFronds\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"shape\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSite\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sYear\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sSiteYear\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"z_bSite\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"parameters\"},{\"name\":\"z_bYear\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nYear) + "},\"block\":\"parameters\"},{\"name\":\"z_bSiteYear\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nSite) + ",\"cols\":" + std::to_string(nYear) + "},\"block\":\"parameters\"},{\"name\":\"bSite\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nSite) + "},\"block\":\"transformed_parameters\"},{\"name\":\"bYear\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nYear) + "},\"block\":\"transformed_parameters\"},{\"name\":\"bSiteYear\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(nSite) + ",\"cols\":" + std::to_string(nYear) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((((1 + 1) + 1) + 1) + 1) + 1) + nSite) +
      nYear) + (nSite * nYear));
    const size_t num_transformed = emit_transformed_parameters * (((nSite +
      nYear) + (nSite * nYear)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((((1 + 1) + 1) + 1) + 1) + 1) + nSite) +
      nYear) + (nSite * nYear));
    const size_t num_transformed = emit_transformed_parameters * (((nSite +
      nYear) + (nSite * nYear)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_weight_macro_namespace::model_weight_macro;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_weight_macro_namespace::profiles__;
}
#endif
#endif
